### ISSUE TITLE
Add sample OWNERS file to repository

### ISSUE THREAD

**Issue by rnjudge** [cncf/project-template#15]
There is broken link reference to an `OWNERS` file in https://github.com/cncf/project-template/blob/main/GOVERNANCE-maintainer.md:

```
[TODO: PROJECTNAME] Maintainers have write access to the [project GitHub repository](TODO).
They can merge their own patches or patches from others. The current maintainers
can be found in [OWNERS](./OWNERS).  Maintainers collectively manage the project's
resources and contributors.
```

However, I do not see an `OWNERS` file in the `cncf/project-template` repository. Would it be possible to provide a sample OWNERS file? From what I've seen, I *think* the file is just the GitHub usernames of the owners? If it doesn't make sense to add a sample `OWNERS` file, perhaps removing the broken link to the file in the `GOVERNANCE-maintainer.md` would be less confusing.

**Comment by carolynvs** [comment]
Last I checked when I went through the sandbox process for my project, the OWNERS file isn't standardized and projects have leeway in how they format it. I have added this to the governance WG agenda to discuss. 

Thank you for bringing up that the link is broken and that we are missing template advice for that file!

**Comment by thisisnotapril** [comment]
Example of maintainers: https://github.com/grpc/grpc/blob/master/MAINTAINERS.md
