### ISSUE TITLE
Add "Governance Amendments" section to federated project template

### ISSUE THREAD

**Issue by asmacdo** [cncf/project-template#30]
Currently, the [federated template](https://github.com/cncf/project-template/blob/main/GOVERNANCE-subprojects.md) does not contain a section for how the governance document should be updated. @jberkus fyi.

Operator Framework is currently [using this template](https://github.com/operator-framework/community/pull/83)

Below is a draft to share what I have in mind, it is a WIP PR. Following the Operator Framework governance merge (and the language below settles), I'd be happy to open a PR here. Suggestions welcome :)

```
## Governance Amendments

The Operator Framework Community may adopt or amend its Governing
Documents according to the following process:

1. Propose a change by opening an issue in the community repository, and if there
   seems to be general agreement, open a pull request to this document.
2. The change should be announced via the mailing list along with an invitation for discussion on the Pull Request.
3. A minimum of 7 days must pass between the announcement and the vote. If there is not consensus, the Steering Committee is encouraged to delay the vote. The Steering Committee can pass the amendment with a 2/3 majority and a minimum quorum of 1/2 of the Committee.
```

**Comment by jberkus** [comment]
Thanks!  That's useful, and makes the template better.

Please hold this as an issue until we merge the big "documentation" PR for the templates.

My suggestion for a more generic version for the template would be something like this:

```
## Amendments

This Governance document, and other governance documents of [$PROJECTNAME], can be amended with a 2/3 majority vote of the Steering Committee.  Unless time is of the essence, the amendment should be circulated in the contributor community for comment for at least one week before voting.
```

Thoughts?

**Comment by jberkus** [comment]
Merged this a while ago, and just remembered to close the issue now.
